export class Task {
  constructor(
    public readonly id: number | null,
    public readonly userId: string,
    public title: string,
    public description: string,
    public completed: boolean,
    public dueDate: Date,
    public comments?: string,
    public responsible?: string,
    public tags?: string[],
  ) {}

  static create(params: {
    userId: string;
    title: string;
    description: string;
    completed: boolean;
    dueDate: Date;
    comments?: string;
    responsible?: string;
    tags?: string[];
  }): Task {
    return new Task(
      null, // id will be generated by the database
      params.userId,
      params.title,
      params.description,
      params.completed,
      params.dueDate,
      params.comments,
      params.responsible,
      params.tags,
    );
  }
}
