export class Task {
  constructor(
    public readonly id: number | null,
    public readonly userId: string,
    public title: string,
    public description: string,
    public completed: boolean,
    public dueDate: Date,
    public isPublic: boolean,
    public comments?: string,
    public responsible?: string,
    public tags?: string[],
    public filePath?: string,
    public fileName?: string,
    public fileSize?: number,
    public fileMimeType?: string,
  ) {}

  static create(params: {
    userId: string;
    title: string;
    description: string;
    completed: boolean;
    dueDate: Date;
    isPublic: boolean;
    comments?: string;
    responsible?: string;
    tags?: string[];
    filePath?: string;
    fileName?: string;
    fileSize?: number;
    fileMimeType?: string;
  }): Task {
    return new Task(
      null, // id will be generated by the database
      params.userId,
      params.title,
      params.description,
      params.completed,
      params.dueDate,
      params.isPublic,
      params.comments,
      params.responsible,
      params.tags,
      params.filePath,
      params.fileName,
      params.fileSize,
      params.fileMimeType,
    );
  }
}
